# Generated by Django 3.1 on 2020-08-26 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_comments_followers_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Followers',
            new_name='Follow',
        ),
    ]
